[tool.poetry]
name = "rpaframework-meta"
version = "0.0.1"
description = "Metapackage for RPA Framework"
authors = [
	"RPA Framework <rpafw@robocorp.com>",
]

[tool.poetry.dependencies]
python = "^3.6"
rpaframework = "6.0.0"
rpaframework-recognition = "0.2.0"
rpaframework-core = "2.1.0"

[tool.poetry.dev-dependencies]
robotframeworklexer = "^1.1"
sphinx = "^2.3.1"
sphinx_rtd_theme = "^0.4.3"
toml = "^0.10.1"
sphinx-markdown-builder = "^0.5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
