name: pip installation tests

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  install_and_check:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: [3.7]
        pip-version: [20.2.4, 20.3.3]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set pip version
        run: python -m pip install --force-reinstall pip==${{matrix.pip-version}}
      - name: install rpafw
        run: python -m pip install rpaframework rpaframework-recognition
      - name: test install is correct
        run: |
          python -m pip check
          python -c "import RPA;"
          # TODO: run whole test suite here

