name: rpaframework-py39
on:
  schedule:
    - cron: 0 0 * * mon
      branches: [master]
defaults:
  run:
    working-directory: './packages/main'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          "windows-py39",
          "ubuntu-py39",
          "macos-py39",
        ]
        include:
          - name: "windows-py39"
            python: "3.9"
            os: windows-latest
          - name: "ubuntu-py39"
            python: "3.9"
            os: ubuntu-latest
          - name: "macos-py39"
            python: "3.9"
            os: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install xclip on linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get update -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install xclip -y
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install poetry
      run: pip install poetry
    - name: Install
      run: make install
    - name: Lint
      run: make lint
    - name: Test on non-linux
      if: matrix.os != 'ubuntu-latest'
      run: make test
    - name: Test on linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        export XDG_SESSION_TYPE=x11
        xvfb-run --server-args="-screen 0 1280x720x24" make test
    - uses: actions/upload-artifact@v1
      if: success() || failure()
      with:
          name: ${{ matrix.os }}-py${{ matrix.python }}-test-reports
          path: packages/main/tests/results
